/**
 * Export Service
 * Handles exporting projects in various formats (Audio, JSON, Markdown, PDF)
 */

import RNFS from 'react-native-fs';
import Share from 'react-native-share';
import {Platform} from 'react-native';
import {AudioProject, ExportFormat} from '@/types/common';

class ExportService {
  private exportPath = Platform.select({
    ios: RNFS.DocumentDirectoryPath,
    android: RNFS.DownloadDirectoryPath,
  })!;

  /**
   * Export project
   */
  async exportProject(
    project: AudioProject,
    format: ExportFormat['format'],
    includeMetadata = true
  ): Promise<string> {
    try {
      console.log(`Exporting project ${project.id} as ${format}`);

      let filePath: string;

      switch (format) {
        case 'json':
          filePath = await this.exportAsJSON(project, includeMetadata);
          break;
        case 'markdown':
          filePath = await this.exportAsMarkdown(project, includeMetadata);
          break;
        case 'pdf':
          filePath = await this.exportAsPDF(project, includeMetadata);
          break;
        case 'audio':
          filePath = await this.exportAsAudio(project);
          break;
        default:
          throw new Error(`Unsupported format: ${format}`);
      }

      console.log('✓ Export complete:', filePath);
      return filePath;
    } catch (error) {
      console.error('❌ Export failed:', error);
      throw error;
    }
  }

  /**
   * Export as JSON
   */
  private async exportAsJSON(
    project: AudioProject,
    includeMetadata: boolean
  ): Promise<string> {
    const fileName = `${this.sanitizeFilename(project.title)}_${Date.now()}.json`;
    const filePath = `${this.exportPath}/${fileName}`;

    const exportData = {
      ...(includeMetadata && {
        exportDate: new Date().toISOString(),
        appVersion: '1.0.0',
        format: 'json',
      }),
      project: {
        id: project.id,
        title: project.title,
        duration: project.duration,
        fileUri: project.fileUri,
        effects: project.effects,
        createdAt: project.createdAt,
        updatedAt: project.updatedAt,
        isFavorite: project.isFavorite,
        tags: project.tags,
      },
    };

    await RNFS.writeFile(filePath, JSON.stringify(exportData, null, 2), 'utf8');

    return filePath;
  }

  /**
   * Export as Markdown
   */
  private async exportAsMarkdown(
    project: AudioProject,
    includeMetadata: boolean
  ): Promise<string> {
    const fileName = `${this.sanitizeFilename(project.title)}_${Date.now()}.md`;
    const filePath = `${this.exportPath}/${fileName}`;

    const markdown = `# ${project.title}

${
  includeMetadata
    ? `**Exported:** ${new Date().toLocaleString()}
**App Version:** 1.0.0

---

`
    : ''
}
## Project Information

- **Duration:** ${this.formatDuration(project.duration)}
- **Created:** ${new Date(project.createdAt).toLocaleString()}
- **Last Modified:** ${new Date(project.updatedAt).toLocaleString()}
- **Favorite:** ${project.isFavorite ? 'Yes' : 'No'}
- **Tags:** ${project.tags.join(', ') || 'None'}

## Applied Effects

${
  project.effects.length > 0
    ? project.effects
        .map(
          (effect, index) =>
            `${index + 1}. **${effect.name}** (${effect.type})
   - Parameters: ${JSON.stringify(effect.parameters, null, 2)}`
        )
        .join('\n\n')
    : 'No effects applied'
}

## File Information

- **File Path:** ${project.fileUri}
- **Project ID:** ${project.id}

---

*Generated by VoiceFX - Offline Voice Effects & Editor*
`;

    await RNFS.writeFile(filePath, markdown, 'utf8');

    return filePath;
  }

  /**
   * Export as PDF
   * Note: Requires react-native-html-to-pdf or similar
   */
  private async exportAsPDF(
    project: AudioProject,
    includeMetadata: boolean
  ): Promise<string> {
    // First create HTML
    const html = this.generateHTML(project, includeMetadata);

    const fileName = `${this.sanitizeFilename(project.title)}_${Date.now()}.pdf`;
    const filePath = `${this.exportPath}/${fileName}`;

    // In production, use react-native-html-to-pdf or similar
    // For now, save as HTML
    const htmlFileName = fileName.replace('.pdf', '.html');
    const htmlFilePath = `${this.exportPath}/${htmlFileName}`;

    await RNFS.writeFile(htmlFilePath, html, 'utf8');

    console.log('PDF export placeholder - saved as HTML:', htmlFilePath);

    return htmlFilePath;
  }

  /**
   * Export as Audio
   * Note: This would copy/process the audio file
   */
  private async exportAsAudio(project: AudioProject): Promise<string> {
    const fileName = `${this.sanitizeFilename(project.title)}_${Date.now()}.wav`;
    const filePath = `${this.exportPath}/${fileName}`;

    // In production, process audio with effects
    // For now, copy original file if it exists
    if (await RNFS.exists(project.fileUri)) {
      await RNFS.copyFile(project.fileUri, filePath);
    } else {
      throw new Error('Source audio file not found');
    }

    return filePath;
  }

  /**
   * Generate HTML for PDF
   */
  private generateHTML(project: AudioProject, includeMetadata: boolean): string {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${project.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
    }
    h1 { color: #007AFF; }
    h2 { color: #333; margin-top: 30px; }
    .metadata { color: #666; font-size: 14px; }
    .effect { margin: 15px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }
    .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${project.title}</h1>

  ${
    includeMetadata
      ? `<div class="metadata">
    <p><strong>Exported:</strong> ${new Date().toLocaleString()}</p>
    <p><strong>App Version:</strong> 1.0.0</p>
  </div>`
      : ''
  }

  <h2>Project Information</h2>
  <ul>
    <li><strong>Duration:</strong> ${this.formatDuration(project.duration)}</li>
    <li><strong>Created:</strong> ${new Date(project.createdAt).toLocaleString()}</li>
    <li><strong>Last Modified:</strong> ${new Date(project.updatedAt).toLocaleString()}</li>
    <li><strong>Favorite:</strong> ${project.isFavorite ? 'Yes' : 'No'}</li>
    <li><strong>Tags:</strong> ${project.tags.join(', ') || 'None'}</li>
  </ul>

  <h2>Applied Effects</h2>
  ${
    project.effects.length > 0
      ? project.effects
          .map(
            effect => `
    <div class="effect">
      <h3>${effect.name} (${effect.type})</h3>
      <pre>${JSON.stringify(effect.parameters, null, 2)}</pre>
    </div>
  `
          )
          .join('')
      : '<p>No effects applied</p>'
  }

  <div class="footer">
    <p>Generated by VoiceFX - Offline Voice Effects & Editor</p>
  </div>
</body>
</html>`;
  }

  /**
   * Share exported file
   */
  async shareFile(filePath: string): Promise<void> {
    try {
      const url = Platform.OS === 'android' ? `file://${filePath}` : filePath;

      await Share.open({
        url,
        type: this.getMimeType(filePath),
        title: 'Share Export',
        subject: 'VoiceFX Project Export',
      });

      console.log('✓ File shared successfully');
    } catch (error) {
      console.error('❌ Failed to share file:', error);
      throw error;
    }
  }

  /**
   * Delete exported file
   */
  async deleteFile(filePath: string): Promise<void> {
    try {
      if (await RNFS.exists(filePath)) {
        await RNFS.unlink(filePath);
        console.log('✓ File deleted:', filePath);
      }
    } catch (error) {
      console.error('❌ Failed to delete file:', error);
      throw error;
    }
  }

  /**
   * Get MIME type from file path
   */
  private getMimeType(filePath: string): string {
    const extension = filePath.split('.').pop()?.toLowerCase();

    const mimeTypes: Record<string, string> = {
      json: 'application/json',
      md: 'text/markdown',
      pdf: 'application/pdf',
      html: 'text/html',
      wav: 'audio/wav',
      mp3: 'audio/mpeg',
    };

    return mimeTypes[extension || ''] || 'application/octet-stream';
  }

  /**
   * Format duration (seconds) to MM:SS
   */
  private formatDuration(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  /**
   * Sanitize filename
   */
  private sanitizeFilename(filename: string): string {
    return filename
      .replace(/[^a-z0-9]/gi, '_')
      .replace(/_+/g, '_')
      .toLowerCase();
  }

  /**
   * Get export directory
   */
  getExportPath(): string {
    return this.exportPath;
  }

  /**
   * List exported files
   */
  async listExportedFiles(): Promise<string[]> {
    try {
      const files = await RNFS.readDir(this.exportPath);
      return files
        .filter(f => f.isFile())
        .map(f => f.path)
        .sort((a, b) => b.localeCompare(a)); // Most recent first
    } catch (error) {
      console.error('Failed to list exported files:', error);
      return [];
    }
  }
}

export const exportService = new ExportService();
